export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_POST = "LOGIN_POST";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_POST = "SIGNUP_POST";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const GET_POST_START = "GET_POST_START";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const GET_ID_POST_START = "GET_ID_POST_START";
export const GET_ID_POST_SUCCESS = "GET_ID_POST_SUCCESS";

export const POST_NEW_POST_START = "POST_NEW_POST_START";
export const POST_NEW_POST_SUCCESS = "POST_NEW_POST_SUCCESS";

export const ADD_INPUT = "ADD_INPUT";

export const DELETE_POST_START = "DELETE_POST_START";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const UPDATE_POST_START = "UPDATE_POST_START";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export const EDIT_POST = "EDIT_POST";
